from math import cos, radians, sin

# Constants
NUM_PLAYERS = 6
NUM_PLAYER_CARDS = 2
NUM_COMMUNITY_CARDS = 5
NUM_FLOP_CARDS = 3
Y_OFFSET = 100
SMALL_BLIND_AMOUNT = 10
BIG_BLIND_AMOUNT = 20
INITIAL_CHIPS = 1000
